[package]
name = "dust-converter-meta"
version = "0.0.0"
edition = "2018"
publish = false
authors = [ "you",]

[dev-dependencies]

[dependencies.dust-converter]
path = ".."

[dependencies.elrond-wasm-debug]
version = "0.38.0"
