// Code generated by the elrond-wasm multi-contract system. DO NOT EDIT.

////////////////////////////////////////////////////
////////////////// AUTO-GENERATED //////////////////
////////////////////////////////////////////////////

// Init:                                 1
// Endpoints:                           35
// Async Callback (empty):               1
// Total number of exported functions:  37

#![no_std]

elrond_wasm_node::wasm_endpoints! {
    dust_converter
    (
        swapDustTokens
        sellDustTokens
        topUp
        extractFees
        setFeePercentage
        setSlippagePercentage
        addKnownTokens
        removeKnownTokens
        getAllTokens
        getTokenThreshold
        getProtocolFeePercent
        getSlippagePercent
        getWrappedTokenId
        getUsdcTokenId
        registerReferralTag
        claimReferralFees
        updateTier
        addTierDetails
        removeTierDetails
        setReferralFeePercentage
        removeReferralTag
        getCollectedFeeAmount
        getUserTag
        getReferralFeePercentage
        getTierDetails
        getTagAccumulatedVolume
        addAdmin
        removeAdmin
        updateOwnerOrAdmin
        getPermissions
        addToPauseWhitelist
        removeFromPauseWhitelist
        pause
        resume
        getState
    )
}

elrond_wasm_node::wasm_empty_callback! {}
