// Code generated by the elrond-wasm multi-contract system. DO NOT EDIT.

////////////////////////////////////////////////////
////////////////// AUTO-GENERATED //////////////////
////////////////////////////////////////////////////

// Init:                                 1
// Endpoints:                           13
// Async Callback (empty):               1
// Total number of exported functions:  15

#![no_std]

elrond_wasm_node::wasm_endpoints! {
    dust_converter
    (
        swapDustTokens
        sellDustTokens
        topUp
        setFeePercentage
        setSlippagePercentage
        addKnownTokens
        removeKnownTokens
        getAllTokens
        getTokenThreshold
        getProtocolFeePercent
        getSlippagePercent
        getWrappedTokenId
        getWrappedTokenAmount
    )
}

elrond_wasm_node::wasm_empty_callback! {}
