// Code generated by the elrond-wasm multi-contract system. DO NOT EDIT.

////////////////////////////////////////////////////
////////////////// AUTO-GENERATED //////////////////
////////////////////////////////////////////////////

// Init:                                 1
// Endpoints:                           24
// Async Callback (empty):               1
// Total number of exported functions:  26

#![no_std]

elrond_wasm_node::wasm_endpoints! {
    dust_converter
    (
        swapDustTokens
        sellDustTokens
        registerReferralTag
        removeReferralTag
        topUp
        extractFees
        setFeePercentage
        setSlippagePercentage
        addKnownTokens
        removeKnownTokens
        setReferralFeePercentage
        getTokenThreshold
        getProtocolFeePercent
        getSlippagePercent
        getWrappedTokenId
        addAdmin
        removeAdmin
        updateOwnerOrAdmin
        getPermissions
        addToPauseWhitelist
        removeFromPauseWhitelist
        pause
        resume
        getState
    )
}

elrond_wasm_node::wasm_empty_callback! {}
